development:
  cloud_name: dnphqhiff
  api_key: '251282792589262'
  api_secret: sSMfL5YYwBx3TzQEChTqMfX-R6M
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dnphqhiff
  api_key: '251282792589262'
  api_secret: sSMfL5YYwBx3TzQEChTqMfX-R6M
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dnphqhiff
  api_key: '251282792589262'
  api_secret: sSMfL5YYwBx3TzQEChTqMfX-R6M
  enhance_image_tag: true
  static_image_support: false
